# Generated by Django 5.0.12 on 2025-02-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='cookie',
            name='image',
        ),
        migrations.AddField(
            model_name='cookie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
